# Generated by Django 5.0.6 on 2024-05-10 08:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_alter_dish_description_alter_menu_day_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
