# Generated by Django 5.0.6 on 2024-05-10 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_vote_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('employee', 'day_of_week')},
        ),
    ]
